import {
  Code,
  Database,
  Palette,
  Server,
  Smartphone,
  Settings,
  GitBranch,
  Shield,
  Brain,
} from 'lucide-react';

export const SKILLS = [
  {
    name: 'React & Next.js',
    percentage: 95,
    icon: <Code className='w-6 h-6' />,
    category: 'Frontend',
    technologies: [
      'React.js',
      'Next.js',
      'SSR/SSG',
      'Redux',
      'Zustand',
      'Context API',
      'Shadcn/ui',
    ],
  },
  {
    name: 'TypeScript & JavaScript',
    percentage: 92,
    icon: <Code className='w-6 h-6' />,
    category: 'Frontend',
    technologies: [
      'TypeScript',
      'JavaScript ES6+',
      'HTML5',
      'CSS3',
      'TailwindCSS',
    ],
  },
  {
    name: 'UI Frameworks & Libraries',
    percentage: 88,
    icon: <Palette className='w-6 h-6' />,
    category: 'Frontend',
    technologies: [
      'Ant Design',
      'Shadcn/ui',
      'Bootstrap',
      'TailwindCSS',
      'i18n',
      'Chart.js',
    ],
  },
  {
    name: 'Backend Development',
    percentage: 88,
    icon: <Server className='w-6 h-6' />,
    category: 'Backend',
    technologies: [
      'Node.js',
      'Express.js',
      'REST APIs',
      'Socket.io',
      'MySQL',
      'MongoDB',
    ],
  },
  {
    name: 'AI & Cloud Services',
    percentage: 80,
    icon: <Brain className='w-6 h-6' />,
    category: 'Backend',
    technologies: [
      'AWS Bedrock',
      'Qdrant',
      'Python',
      'DigitalOcean',
      'Cloudinary',
      'PayOS',
    ],
  },
  {
    name: 'Mobile Development',
    percentage: 88,
    icon: <Smartphone className='w-6 h-6' />,
    category: 'Mobile',
    technologies: [
      'React Native',
      'Expo',
      'NativeWind',
      'Reanimated 2',
      'EAS Build',
      'Deep Linking',
    ],
  },
  {
    name: 'Mobile Services',
    percentage: 85,
    icon: <Smartphone className='w-6 h-6' />,
    category: 'Mobile',
    technologies: [
      'Google Maps SDK',
      'Firebase Auth',
      'Firebase Storage',
      'FCM',
      'Push Notifications',
      'Sentry',
    ],
  },
  {
    name: 'State Management & Query',
    percentage: 85,
    icon: <Database className='w-6 h-6' />,
    category: 'Frontend',
    technologies: [
      'TanStack Query',
      'Zustand',
      'Redux Toolkit',
      'Context API',
      'React Hook Form',
      'Zod',
    ],
  },
  {
    name: 'DevOps & Tools',
    percentage: 82,
    icon: <Settings className='w-6 h-6' />,
    category: 'Tools',
    technologies: [
      'Docker',
      'Git',
      'GitHub Actions',
      'Supabase',
      'Firebase',
      'Sentry',
      'Jest',
    ],
  },
  {
    name: 'Design & Workflow',
    percentage: 80,
    icon: <Palette className='w-6 h-6' />,
    category: 'Tools',
    technologies: [
      'Figma',
      'Agile/Scrum',
      'Jira',
      'Accessibility (A11y)',
    ],
  },
];
