export const WORK_EXPERIENCES = [
  {
    id: 1,
    company: 'FPT Software',
    position: 'Frontend Developer',
    description:
      'Developing and maintaining web applications using React, Next.js, and TypeScript.',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    location: 'Ho Chi Minh City, Vietnam',
    logo: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
    link: 'https://www.google.com',
    tech: [
      'React',
      'NextJS',
      'TailwindCSS',
      'TypeScript',
      'Node.js',
      'MongoDB',
      'PostgreSQL',
      'Docker',
      'Kubernetes',
    ],
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 2,
    company: 'FPT Software',
    position: 'Frontend Developer',
    description:
      'Developing and maintaining web applications using React, Next.js, and TypeScript.',
    startDate: '2021-01-01',
    endDate: '2021-01-01',
    location: 'Ho Chi Minh City, Vietnam',
    logo: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
    link: 'https://www.google.com',
    tech: [
      'React',
      'NextJS',
      'TailwindCSS',
      'TypeScript',
      'Node.js',
      'MongoDB',
      'PostgreSQL',
      'Docker',
      'Kubernetes',
    ],
    color: 'from-blue-500 to-cyan-500',
  },
];
