export const WORK_EXPERIENCES = [
  {
    id: 1,
    company: 'Tiximax',
    position: 'Frontend Developer',
    description:
      'Developed a multi-tenant SaaS timekeeping system with complex shift scheduling and overtime logic, reducing manual processing by 30% across multiple clients. Built a RAG-based AI assistant using AWS Bedrock and vector database (Qdrant), reducing average customer response time from 2 minutes to under 30 seconds. Collaborated on UI/UX design using Figma for a used-car marketplace platform.',
    startDate: '2025-09',
    endDate: '2026-03',
    location: 'Ho Chi Minh City, Vietnam',
    logo: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&h=300&fit=crop',
    link: 'https://www.google.com',
    tech: [
      'Next.js',
      'Ant Design',
      'TanStack Query',
      'i18n',
      'Python',
      'AWS Bedrock',
      'Qdrant',
      'Figma',
      'GitHub',
    ],
    color: 'from-purple-500 to-indigo-500',
  },
  {
    id: 2,
    company: 'CEH',
    position: 'Frontend Developer Intern',
    description:
      'Implemented master data for a Marine Equipment Management System using ReactJS and jQuery, reducing management time by 20%. Resolved cross-browser UI inconsistencies using Chrome DevTools and responsive debugging, improving UX consistency across major browsers. Designed Figma UI prototypes for the Terminal Operation System, improving development efficiency by 35%. Coordinated closely with Backend Engineers and PMs under the Agile/Scrum process to deliver new features.',
    startDate: '2024-10',
    endDate: '2025-01',
    location: 'Ho Chi Minh City, Vietnam',
    logo: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
    link: 'https://www.google.com',
    tech: [
      'React.js',
      'Bootstrap 4',
      'jQuery',
      'Git',
      'GitLab',
      'RESTful APIs',
      'Jira',
      'Figma',
    ],
    color: 'from-blue-500 to-cyan-500',
  },
];
